// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Repository struct {
	ID              int32
	FullName        string
	Description     pgtype.Text
	StargazersCount int32
	ForksCount      int32
	CreatedAt       pgtype.Timestamptz
	RepoStatus      string
	ErrorCode       pgtype.Text
	UpdatedAt       pgtype.Timestamptz
}
