// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRepo = `-- name: GetRepo :one
SELECT id, full_name, description, stargazers_count, forks_count, created_at
FROM repositories
WHERE full_name = $1
LIMIT 1
`

func (q *Queries) GetRepo(ctx context.Context, fullName string) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepo, fullName)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Description,
		&i.StargazersCount,
		&i.ForksCount,
		&i.CreatedAt,
	)
	return i, err
}

const insertRepo = `-- name: InsertRepo :exec
INSERT INTO repositories (
        full_name,
        description,
        stargazers_count,
        forks_count,
        created_at
    )
VALUES ($1, $2, $3, $4, $5) ON CONFLICT (full_name) DO
UPDATE
SET description = EXCLUDED.description,
    stargazers_count = EXCLUDED.stargazers_count,
    forks_count = EXCLUDED.forks_count,
    created_at = EXCLUDED.created_at
`

type InsertRepoParams struct {
	FullName        string
	Description     pgtype.Text
	StargazersCount int32
	ForksCount      int32
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertRepo(ctx context.Context, arg InsertRepoParams) error {
	_, err := q.db.Exec(ctx, insertRepo,
		arg.FullName,
		arg.Description,
		arg.StargazersCount,
		arg.ForksCount,
		arg.CreatedAt,
	)
	return err
}

const listAllRepos = `-- name: ListAllRepos :many
SELECT id, full_name, description, stargazers_count, forks_count, created_at
FROM repositories
ORDER BY full_name
`

func (q *Queries) ListAllRepos(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listAllRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Description,
			&i.StargazersCount,
			&i.ForksCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
