// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	GetRepo(ctx context.Context, fullName string) (Repository, error)
	GetReposByNames(ctx context.Context, dollar_1 []string) ([]Repository, error)
	InsertRepo(ctx context.Context, arg InsertRepoParams) error
	ListAllRepos(ctx context.Context) ([]Repository, error)
	UpdateRepoStatus(ctx context.Context, arg UpdateRepoStatusParams) error
}

var _ Querier = (*Queries)(nil)
