app:
  app_name: "repo-watcher-collector"

grpc:
  address: "localhost:8082"
  timeout: "5s"

github:
  timeout: "5s"

kafka:
  address: "kafka:9092"
  producer_topic: "repo-results"
  consumer_topic: "repo-requests"
  group_id: "collector-group"

subscription_updater:
  interval: "15s"

logger:
  log_level: "DEBUG"

services:
  subscriber: "localhost:8081"
