// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/collector/collector.proto

package collectorv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepoRequest) Reset() {
	*x = GetRepoRequest{}
	mi := &file_proto_collector_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepoRequest) ProtoMessage() {}

func (x *GetRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepoRequest.ProtoReflect.Descriptor instead.
func (*GetRepoRequest) Descriptor() ([]byte, []int) {
	return file_proto_collector_collector_proto_rawDescGZIP(), []int{0}
}

func (x *GetRepoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRepoRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type GetRepoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Repo            string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StargazersCount int32                  `protobuf:"varint,4,opt,name=stargazers_count,json=stargazersCount,proto3" json:"stargazers_count,omitempty"`
	ForksCount      int32                  `protobuf:"varint,5,opt,name=forks_count,json=forksCount,proto3" json:"forks_count,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRepoResponse) Reset() {
	*x = GetRepoResponse{}
	mi := &file_proto_collector_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepoResponse) ProtoMessage() {}

func (x *GetRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collector_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepoResponse.ProtoReflect.Descriptor instead.
func (*GetRepoResponse) Descriptor() ([]byte, []int) {
	return file_proto_collector_collector_proto_rawDescGZIP(), []int{1}
}

func (x *GetRepoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRepoResponse) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *GetRepoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetRepoResponse) GetStargazersCount() int32 {
	if x != nil {
		return x.StargazersCount
	}
	return 0
}

func (x *GetRepoResponse) GetForksCount() int32 {
	if x != nil {
		return x.ForksCount
	}
	return 0
}

func (x *GetRepoResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_proto_collector_collector_proto protoreflect.FileDescriptor

const file_proto_collector_collector_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/collector/collector.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n" +
	"\x0eGetRepoRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"\xe2\x01\n" +
	"\x0fGetRepoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\x10stargazers_count\x18\x04 \x01(\x05R\x0fstargazersCount\x12\x1f\n" +
	"\vforks_count\x18\x05 \x01(\x05R\n" +
	"forksCount\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2C\n" +
	"\vRepoService\x124\n" +
	"\aGetRepo\x12\x13.api.GetRepoRequest\x1a\x14.api.GetRepoResponseB1Z/repo-stat/proto/gen/go/collector/v1;collectorv1b\x06proto3"

var (
	file_proto_collector_collector_proto_rawDescOnce sync.Once
	file_proto_collector_collector_proto_rawDescData []byte
)

func file_proto_collector_collector_proto_rawDescGZIP() []byte {
	file_proto_collector_collector_proto_rawDescOnce.Do(func() {
		file_proto_collector_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_collector_collector_proto_rawDesc), len(file_proto_collector_collector_proto_rawDesc)))
	})
	return file_proto_collector_collector_proto_rawDescData
}

var file_proto_collector_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_collector_collector_proto_goTypes = []any{
	(*GetRepoRequest)(nil),        // 0: api.GetRepoRequest
	(*GetRepoResponse)(nil),       // 1: api.GetRepoResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_collector_collector_proto_depIdxs = []int32{
	2, // 0: api.GetRepoResponse.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: api.RepoService.GetRepo:input_type -> api.GetRepoRequest
	1, // 2: api.RepoService.GetRepo:output_type -> api.GetRepoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_collector_collector_proto_init() }
func file_proto_collector_collector_proto_init() {
	if File_proto_collector_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_collector_collector_proto_rawDesc), len(file_proto_collector_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_collector_collector_proto_goTypes,
		DependencyIndexes: file_proto_collector_collector_proto_depIdxs,
		MessageInfos:      file_proto_collector_collector_proto_msgTypes,
	}.Build()
	File_proto_collector_collector_proto = out.File
	file_proto_collector_collector_proto_goTypes = nil
	file_proto_collector_collector_proto_depIdxs = nil
}
