// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (int64, error)
	ListSubscriptions(ctx context.Context) ([]Subscription, error)
}

var _ Querier = (*Queries)(nil)
